### ISSUE TITLE
Modelling Root Lesion Nematode Population Densities in R

### ISSUE THREAD

**Issue by adamhsparks** [openplantpathology/contributions#1]
### Summary

- What are you contributing to Open Plant Pathology? (explain in 50
words or less):

Blog post describing how to recreate models of nematode populations as described by J. Thompson (2015) in Field Crops Research using R. This is an instructional post just to demonstrate working with data, visualising and fitting and interpreting models. Most of the epidemiology is left to the reader to read the original paper, however some background information is provided.

- URL for the contribution (the development repository, not a stylized html page
forked from this repository): 
https://github.com/adamhsparks/Modelling_Nematode_Populations

- Please indicate which category or categories this contribution falls under,
["teaching", "community", "reproducible research"]

teaching, reproducible research

### Requirements

Confirm each of the following by checking the box.  This contribution:

- [x] does not violate the Terms of Service of any service it may interact with.
- [x] I agree to abide by [Open Plant Pathology's Code of Conduct](conduct.md)
during the review process and in providing any updates or modifications as
necessary after publication.

### Detail

- If possible, please provide recommendations of reviewers - those who have a
good working knowledge of the subject matter you've prepared - and their GitHub
user names:

Emerson Del Ponte, @emdelponte

Mladen Çucak, @mladencucak

**Comment by adamhsparks** [comment]
Our first review! I've assigned @mladencucak  and @emdelponte.

For this repository, I've setup instructions for reviewers, https://github.com/openplantpathology/contributions/blob/master/reviewer_materials/reviewer_guide.md. Can the two of you please look over the instructions and help me with making them more clear or adding missing information as you go through the review process?

When you submit your review, please submit it here as a response to this issue using the template provided, https://github.com/openplantpathology/contributions/blob/master/reviewer_materials/reviewer_template.md. Copy, paste and fill it in here. Again, please help me with making that more clear, fill in what you think may be missing, etc.

Thanks for agreeing to be a part of this!

**Comment by mladencucak** [comment]
Content Review
Please check off boxes as applicable, and elaborate in comments below. Your review is not limited to these topics, as described in the reviewer guide

 As the reviewer I confirm that there are no conflicts of interest for me to review this work (If you are unsure whether you are in conflict, please check with Emerson or Adam before starting your review).
Content
The content meets the following criteria:

 [x] A statement of objectives, the content has clearly stated objectives.
 [x]Meets the stated objectives, the content clearly illustrates the stated objectives.
 [x]Is unique, the content presents new material or discussion is presented in the content.
 [x]Clearly written and easily understandable, the content is easily understood by a general audience.
 [x]The code is clearly written and easy to understand, there is no extra code and all code is described appropriately.
 [x]Spelling and grammar are correct, the content is free from major spelling and grammatical errors.
[x] The demonstrated code is a good illustration of the methods, while other methods may exist, this is a good example and easy to follow.
Final approval (post-review)
 The author has responded to my review and made changes to my satisfaction. I recommend approving this package.
Estimated hours spent reviewing:
3h (approx. 1.5 on the content itself, since I had to understand the reviewing process itself) 

Review Comments

As this is the first blog and we are still searching for most appropriate delivery mechanism, I think this post (with some changes and upgrades) is very useful, structured and informative post. I have a few 'content' related and technical comments. 

Content related: 
I have found it hard to understand the data and the study without the original paper. Maybe one sentence from  the paper, chapter 2.1. would make it more 'stand alone' valuable. 
In the introduction, 2nd paragraph, I would say that the aim of study is to determine optimum sowing dates, rather than investigation being aim of the study. Perhaps, it is obvious but objective of the post itself is not really clear. I would suggest a sentence on that even before introduction.  
As said before, more description of model diagnostics, since the main theme of the post is fitting models into data. Also, maybe in conclusions, some reflection onto difference between linear and quadratic model fit to this data set. 
[Fitting_Nematode_Models_Mladen.docx](https://github.com/openplantpathology/contributions/files/1692888/Fitting_Nematode_Models_Mladen.docx)


Technical comments: 
- Reshaping data: I prefer seeing comments in code when it comes to description of what each line does, especially for dplyr pipeline. Maybe use text above to say why and what is happening in background, while step by step adding as a comment. 
- Should there be more explanation about grouping for ploting 
- Consider saving plots as objects. 
- Think about using  `knitr::write_bib()` at the end of the document.

**Comment by emdelponte** [comment]
## Content Review

*Please check off boxes as applicable, and elaborate in comments below. Your
review is not limited to these topics, as described in the reviewer guide*

- [ ] As the reviewer I confirm that there are no conflicts of interest for me
to review this work (If you are unsure whether you are in conflict, please check
with Emerson or Adam _before_ starting your review).

#### Content

The content meets the following criteria:

- [ ] **A statement of objectives**, the content has clearly stated objectives.
- [ ] **Meets the stated objectives**, the content clearly illustrates the
stated objectives.
- [ ] **Is unique**, the content presents new material or discussion is
presented in the content.
- [ ] **Clearly written and easily understandable**, the content is easily
understood by a general audience.
- [ ] **The code is clearly written and easy to understand**, there is no extra
code and all code is described appropriately.
- [ ] **Spelling and grammar are correct**, the content is free from major
spelling and grammatical errors.
- [ ] **The demonstrated code is a good illustration of the methods**, while
other methods may exist, this is a good example and easy to follow.

#### Final approval (post-review)

- [ ] **The author has responded to my review and made changes to my
satisfaction. I recommend approving this package.**

Estimated hours spent reviewing:  3h

---

### Review Comments

The teaching note illustrates well how to reproduce the statistical analysis and obtain the same results of the original study using R . As we are defining the best shape for this kind of contribution for OPP, I have several suggestions related to structure besides a few related to the content.  They are referenced by the line number in the original Rmd file. 

L2 - Suggestion: **Linear modelling of soil temperature effects on root lesion nematode population densities in R**

L15 - Suggest moving the reference to the end of the document to avoid duplication

L23-39 For this kind of teaching note where the objective is to demonstrate how to repeat or conduct new analysis using published data in R, the first lines of the introduction should not read like the original paper, but something more similar to the second paragraph. As the post is HTML, and it will be a blog post actually, hyperlinks to external references are very useful for the reader interested in further information beyond the paper. For example, link to an APS material or similar fact-sheet about the nematode, symptoms, etc. Most of the objectives should be moved to introduction. Don't think a separate section for objective is necessary, since it is quite obvious and will repeat for most similar posts: recreate the analysis in R.. 

L46-47 No need to show this link or suggestion here but at the end in a section like "Suggested reading" or "Recommended reading" prior to references.

L51 - Why not place the references in a `.bib` file? I know that they are only two, but could be more.

L56-58 - Each note will have particularities on the structure and steps for analysis with R, but we should consider a standard template to agree and follow. My suggestion is:

- Introduction
- Packages
- Data wrangling (includes import, clean, transform from raw..)
- Data visualization
- Modeling
- Communication (nice static of interactive plots for publication)
- Conclusion
- Recommended reading
- References

L72 - Is there any place in the code where a seed is needed?

L80 - Why you are using long name with spaces? was this the file name given by the collaborator? any convention on file names that would be interesting to mention? 

note: I found very useful to use the [`here`](https://github.com/jennybc/here_here) package for the reasons explained in the authors page. 

L82 - Although the standard `tibble` presentation is a nice summary, a possibility is the `printr` package to show the data in a format not affected by screen size.

L85 - Consider an R Markdown table for better presentation

L109 - I found the explanation of `gather` too long  or not necessary for the objective of the note. 
Suggested links:
https://blog.rstudio.com/2014/07/22/introducing-tidyr/
http://tidyr.tidyverse.org/reference/gather.html

L120 - why not pipe all the way! 

`nema_long <- nema %>% 
        gather(Variety, Population, Unplanted:Suneca)`

Consider using `log_pop` instead of `population` as column name. 

L126 - If you decide to use `printr`, considering using `head(x, 10)`

L129 - Wondering if it would be interesting/necessary to visually explore a bit more the raw data prior to visual inspection of population densities over time?

L130 - any technical reason for the smoothed line? expect that a beginner will understand it?  is the SE needed?

L132 - Consider the use of color and a single shape (filled circle) for temperature from cold to warm for a nice nature effect and discrimination of temperatures visually. I think `viridis` would work. Use `facet_wrap` by variety for improved visualization.

L159 - I understand that you are reproducing what has been done in the paper and taking the chance to demonstrate how to do things in R. However, either second order or first order would work here. Perhaps biologically stick with the second order would be best option. Statistically the AIC is almost the same. Perhaps make some comments in this regard?

L196 - Isn't this default when calling the plot when running this in R Studio?

L189 - The purpose is to show how to fit linear models, but it may be important for the beginner some help to understand the diagnostic plot and have some links to pages where further explanation can be found. Provide links to Faraway and other useful tutorials on the web.

L236 - Suggestion: "..original paper, the quadratic model best described Gatcher and GS50a data"

L343 - A conclusion should appear as wrap-up for the exercise, what was learned, what could be made differently than was done by the authors, etc. Perhaps at the beginning of the note state clearly what is the target user or level of knowledge required, something like beginner, advanced, etc.

Instead of hand-code the equations why not get the vectors from `lm()` output?

L354 - The `glance` or `tidy` functions of the `broom` package could be helpful here 

L357 - Consider a "recommended reading section" prior to the references.

L372 - Session info reveals the amount of packages not used. Consider loading only the four packages within tidyverse that will be used.

**Comment by adamhsparks** [comment]
Thanks @mladencucak and @emdelponte!

Good stuff. I've found several shortcomings in the original document that you've discovered in your reviews, as well as a few others that you didn't point out, but have made me realise.

I'm working on updating it now, it will take me some time, but I think we'll end up with a much better end-product thanks to your efforts!

**Comment by adamhsparks** [comment]
@emdelponte a few ?? for you.

> L129 - Wondering if it would be interesting/necessary to visually explore a bit more the raw data prior to visual inspection of population densities over time?

What sort of exploration more would you like to suggest? 

> L130 - any technical reason for the smoothed line? expect that a beginner will understand it? is the SE needed?

Can remove the SE, yes. Just thought adding it does make it more clear why one model is a straight line and the other quadratic.

> L196 - Isn't this default when calling the plot when running this in R Studio?

I get the typical: `Hit <Return> to see next plot: ` if I don't set the column and rows?

> L357 - Consider a "recommended reading section" prior to the references.

What sort of recommded reading do you think would be appropriate here? I was thinking it was covered in the introduction with reference to the Faraway book. 

> L372 - Session info reveals the amount of packages not used. Consider loading only the four packages within tidyverse that will be used.

Could do that, just seemed easier to load one package rather than several for simplicity's sake.

**Comment by adamhsparks** [comment]
@mladencucak,
Could I ask you to edit your review and pull the comments out of the Word document and post them in this thread in the same fashion that Emerson has?

Since I've been editing it, you can view the original file for review here: https://github.com/adamhsparks/Modelling_Nematode_Populations/blob/ab3f8ec105ca76e115886f3ada099ed7fdb9451c/Fitting_Nematode_Models.Rmd to get the line numbers, etc.

**Comment by emdelponte** [comment]
@adamhsparks my answers below

> What advantage does the `here` package offer over just loading the data as I have done (here). Hah!

Not much, it was a note that something to consider for further use for situations with multiple folders and to ensure reproducibility. In your note, you could have img folder with subfolder like png and tiff. The advantage is that the full path is not needed. In fact, final section on communication would be nice where you could show how to replicate Fig 2 of the paper using R and produce a high quality `png`file. It would be a nice addition. Consider make clear in the introduction that the models fitted in this note only a portion of what has been done in the paper.

> I tend to name files fairly descriptively, I see little reason to not use spaces in them with current operating systems. But I wasn't planning to go into file naming in this post, that could be a whole other post... Is there something specific here that you think is missing or it's just a "maybe this would be nice"?

No need to explain naming system. I was just curious the convention you were following. Eventually we need to load several files and the long descriptive names will require extra typing effort.

> What sort of exploration more would you like to suggest? 

Since the note is about linear modelling, found interesting to explore reasons for the use of log.  Something like this with or without faceting, showing original and transformed data. The original data is quite skewed towards zero (due to unplanted). It seems heterocedasticity using original data is more problematic?

```
nema_long %>% 
  ggplot(aes(Variety, exp(Population)))+
  geom_boxplot(outlier.colour = NA)+
  geom_jitter(width=.1)+
  facet_wrap(~Temperature)
```

> Can remove the SE, yes. Just thought adding it does make it more clear why one model is a straight line and the other quadratic.

This is one of the explanations for exploring patterns using smooth. Consider adding some sort or comment about this and interested reader can follow a link to know more about smoothing. It is subject for another note! but once it is there, a comment may be worth.

> I get the typical: `Hit <Return> to see next plot: ` if I don't set the column and rows?

I was thinking of the outputs, not running in the environment. But you are right, in html they keep in one column. Keep it there.

> What sort of recommended reading do you think would be appropriate here? I was thinking it was covered in the introduction with reference to the Faraway book. 

Other well written blog posts related to linear modelling or even links to other temperature-driven models in R?

> Could do that, just seemed easier to load one package rather than several for simplicity's sake.

That is what I usually do, but just wondered if non-tidyversed reader would be confused when glancing over the long list of packages loaded in the session.

**Comment by mladencucak** [comment]
@emdelponte @adamhsparks 
Maybe this is a topic for the contribution channel but since you have already started a discussion about some general template for the blog contributions. Not all posts will be strictly some kind of modeling and similar to this one. As you suggested there should be exercises of different level...

1. Intro
     - What is done - some theory and background info. 
2. The data or/and methods
     - Packages 
     - Data wrangling (includes import, clean, transform from raw..)
     - Data visualization
3.  Something that is done - Visualization(s) could be main point of the exercise. 
4. Conclusions
Not sure about recommended reading here - maybe rather see that in introduction as some links, or just citing and then putting it together with references. 
5. References

**Comment by emdelponte** [comment]
Thanks @mladencucak  for the comments. I agree that a one-size-fits-all template will be hard, but the logic/ordered steps will not change and some will definitely not appear in the note  as you said. Whatever the content is, as far as R code is regards, there will be:

Introduction/context/problem, packages to load, data wrangling, data visualization, modeling (optional), communication (also optional - not referring to plots for data visualization, but preparation of static of interactive plots of publication. Summary tables are also communication) and a conclusion. 

What you propose in 2 and 3 aren't the same step?

**Comment by mladencucak** [comment]
Well, not necessarily , Importing/sorting/visualizing data would fall into different group from something like modeling in this case. Of course this could be interpreted in may ways. My main point is: 
1. Present the topic
2. Get the data, prepare and visualize - importing could be even bigger part then organizing (I'm just importing 25 w. stations with metadata...). For me these are all preparation steps..
3. Do something with it and communicate
4. Communicate and/or Conclude 
5. Refer to other work

Steps 3 and 4 could end up together - and it is maybe even better if you have number of models to give short reflection straight below the result and then write an overall conclusion maybe supported by some table? 
Just bouncing ideas...

**Comment by emdelponte** [comment]
Your revision of the topics follows the steps I presented :)  so there is a basic structure/flow to agree upon:  formulate a question/objective >  get data > wrangle data > do what is needed to answer the question > communicate the findings > conclude > give credits. 

Originally, I was wondering how to split and name the sections and whether they should be standardized as a suggestion for future teaching notes.

**Comment by adamhsparks** [comment]
I don't see why the couldn't be standardised. We do this with journal articles. It would make following teaching materials easier.

Also should standardise the English used, perhaps? I'm aware that I'm using Australian English rather than American...

**Comment by mladencucak** [comment]
Not disagreeing, just suggesting onehigher order of hiearchy, but let this resolve itself over time. 

English...I am non native speaker, who is used to Us English, lately mixing Irish and UK English. Someone will have to do a big cleanup after me... :)

**Comment by adamhsparks** [comment]
Thanks @emdelponte and @mladencucak for the thorough feedback and reviews. Your careful consideration and thoughts on this have really made it a much better work.

Based on your feedback, I have:

- Added a bibliography file: https://github.com/adamhsparks/Modelling_Nematode_Populations/commit/4e81b6646cd031d08752369e0ca06f57082912f1

- Updated the section headings: https://github.com/adamhsparks/Modelling_Nematode_Populations/commit/71bfc6b88ad75d496d6f7d1e16e396390b19b322

- Removed `set.seed()`: https://github.com/adamhsparks/Modelling_Nematode_Populations/commit/71bfc6b88ad75d496d6f7d1e16e396390b19b322

- Renamed "Population" to "Log_pop": https://github.com/adamhsparks/Modelling_Nematode_Populations/commit/e97434716ace424b97892e578a1e073c7052377a

- Changed the graphs to use `facet_wrap()` for displaying data: https://github.com/adamhsparks/Modelling_Nematode_Populations/commit/1980c51b5653e0fc2bb500389ad17a40a9a012e7

- Used `%>%` for the `gather()` function: https://github.com/adamhsparks/Modelling_Nematode_Populations/commit/8320906a63f00f3ec4ec9ab649f54ce7f92baa19

- Used a table rather than a list to describe the fields in the `nema` data: https://github.com/adamhsparks/Modelling_Nematode_Populations/commit/ae508337ec43a63cf009f6b44f7df59faca1d0b6 and https://github.com/adamhsparks/Modelling_Nematode_Populations/commit/878f35f6198ba5ca7507e8255ae0da96e4f8aa81

- Cleaned up the description of the **`tidyverse`**

- Corrected missing "wide to long", referred to by @mladencucak and added more detail about tidy data with Wickham 2014 refere https://github.com/adamhsparks/Modelling_Nematode_Populations/commit/5923e23093a16eefde31673a458438a7731d95b0

- Renamed the CSV file following the suggesions of @grunwald labs reproducible research guidelines

- Add "Bonus Materials" section with details on using AIC to fit models and why the data were log transformed: https://github.com/adamhsparks/Modelling_Nematode_Populations/commit/a751ab6ccd02083986449ccb77a25f8f140f2f11, https://github.com/adamhsparks/Modelling_Nematode_Populations/commit/d7ff1bdb7d4de50fa587a6da1f43e50a553e72d2, https://github.com/adamhsparks/Modelling_Nematode_Populations/commit/5376fc07576720cbc8d71d505d29682ce5880e29 and https://github.com/adamhsparks/Modelling_Nematode_Populations/commit/966cc64ead72ed0b9b0f065f130a2fe9a9f97b02

- Use **`printr`** for prettier R output: https://github.com/adamhsparks/Modelling_Nematode_Populations/commit/cd7791bec5c042a391d640b7fa86867e9e5de234

- Use only CRAN available packages: not dev versions: https://github.com/adamhsparks/Modelling_Nematode_Populations/commit/cd7791bec5c042a391d640b7fa86867e9e5de234

- Check if packages are installed, if not install on-the-fly: https://github.com/adamhsparks/Modelling_Nematode_Populations/commit/cd7791bec5c042a391d640b7fa86867e9e5de234

- Add materials to Further Reading section for

    - Interpreting qq-plots

    - Interpreting `lm()` diagnostic plots

    - Interpreting `summary(lm.object)`

    - Choosing colour schemes

    - Tidy data:
https://github.com/adamhsparks/Modelling_Nematode_Populations/commit/cd7791bec5c042a391d640b7fa86867e9e5de234

**Comment by emdelponte** [comment]
Good job @adamhsparks. Changes approved. 

Just a note:
The `nema` dataframe is showing OK using `printr` but the `head(nema_long)` is not printing as `nema`.

**Comment by mladencucak** [comment]
Wow, this has grown a bit, thanks for taking our comments into consideration. 
Just take a look at first line in section Quadratic models: 'In the original paper, original paper '
Something to think about is referencing to outside sources, blog bosts vs. book chapters of some reproducible R Stats books.

**Comment by adamhsparks** [comment]
@emdelponte, I thought so with the `nema_long`, wasn't sure though. Not sure what's going on there? I'll dig into it. I think it's be cause I loaded **`kableExtra`** in the prior code chunk and that might be over riding the settings.

@mladencucak, thanks for catching the "original paper" thing.

**Comment by adamhsparks** [comment]
Sorry, hit the wrong button. Still drinking my coffee this morning. Didn't mean to close this yet.

**Comment by adamhsparks** [comment]
I've fixed the table formatting issue, but now `printr` won't display the headings properly. :/

Note that the "V" from Variety is included in the "Degree_days" table header. I have no idea.

`html
<tr class="header">
<th style="text-align: left;">Weeks</th>
<th style="text-align: left;">Days</th>
<th style="text-align: left;">Temperature</th>
<th>Degree_days V</th>
<th style="text-align: left;">ariety</th>
<th style="text-align: left;">Log_pop</th>
</tr>
`

**Comment by emdelponte** [comment]
cool! I think you are ready to go. Let's see how these formatting issues appear as blog post in our academic hugo theme.

**Comment by adamhsparks** [comment]
Final approval with minor edits recieved from co-author J. Thompson.

I've drafted a new release v1.0.0, it's ready to publish.

**Comment by adamhsparks** [comment]
Code for review badge to be placed to right of DOI.

[![](https://img.shields.io/badge/OPP-Peer%20Reviewed-brightgreen.svg)](https://github.com/openplantpathology/contributions/issues/1)
